export const property=[
    {
        id:1,
        propertyName:'Experion The Westerlies',
        location:'St. 163, Sector-108 Gurgaon',
        feild1:'Developer Name',
        feild2:'Client Name',
        feild3:'Attendee Name',
        // feild4:'Unit Number',
        feild5:'Request Date',
        feild6:'Status',
        BrokerName:'Rajan Pathak',
        ClientName:'Abhinav',
        Attendee:'Umair',
        // UnitNumber:'12A',
        RequestDate:'12-04-2020',
        Status:'Pending'
    },
    {
        id:2,
        propertyName:'Experion The Westerlies',
        location:'St. 163, Sector-108 Gurgaon',
        feild1:'Developer Name',
        feild2:'Client Name',
        feild3:'Attendee Name',
        // feild4:'Unit Number',
        feild5:'Request Date',
        feild6:'Status',
        BrokerName:'Rajan Pathak',
        ClientName:'Abhinav',
        Attendee:'Umair',
        // UnitNumber:'12A',
        RequestDate:'12-04-2020',
        Status:'Pending'
    },
    {
        id:3,
        propertyName:'Experion The Westerlies',
        location:'St. 163, Sector-108 Gurgaon',
        feild1:'Developer Name',
        feild2:'Client Name',
        feild3:'Attendee Name',
        // feild4:'Unit Number',
        feild5:'Request Date',
        feild6:'Status',
        BrokerName:'Rajan Pathak',
        ClientName:'Abhinav',
        Attendee:'Umair',
        // UnitNumber:'12A',
        RequestDate:'12-04-2020',
        Status:'Approved'
    },
    {
        id:4,
        propertyName:'Experion The Westerlies',
        location:'St. 163, Sector-108 Gurgaon',
        feild1:'Developer Name',
        feild2:'Client Name',
        feild3:'Attendee Name',
        // feild4:'Unit Number',
        feild5:'Request Date',
        feild6:'Status',
        BrokerName:'Rajan Pathak',
        ClientName:'Abhinav',
        Attendee:'Umair',
        // UnitNumber:'12A',
        RequestDate:'12-04-2020',
        Status:'Pending'
    },
    {
        id:5,
        propertyName:'Experion The Westerlies',
        location:'St. 163, Sector-108 Gurgaon',
        feild1:'Developer Name',
        feild2:'Client Name',
        feild3:'Attendee Name',
        // feild4:'Unit Number',
        feild5:'Request Date',
        feild6:'Status',
        BrokerName:'Rajan Pathak',
        ClientName:'Abhinav',
        Attendee:'Umair',
        // UnitNumber:'12A',
        RequestDate:'12-04-2020',
        Status:'Pending'
    },
    {
        id:6,
        propertyName:'Experion The Westerlies',
        location:'St. 163, Sector-108 Gurgaon',
        feild1:'Developer Name',
        feild2:'Client Name',
        feild3:'Attendee Name',
        // feild4:'Unit Number',
        feild5:'Request Date',
        feild6:'Status',
        BrokerName:'Rajan Pathak',
        ClientName:'Abhinav',
        Attendee:'Umair',
        // UnitNumber:'12A',
        RequestDate:'12-04-2020',
        Status:'Pending'
    },
    {
        id:7,
        propertyName:'Experion The Westerlies',
        location:'St. 163, Sector-108 Gurgaon',
        feild1:'Developer Name',
        feild2:'Client Name',
        feild3:'Attendee Name',
        // feild4:'Unit Number',
        feild5:'Request Date',
        feild6:'Status',
        BrokerName:'Rajan Pathak',
        ClientName:'Abhinav',
        Attendee:'Umair',
        // UnitNumber:'12A',
        RequestDate:'11-04-2020',
        Status:'Rewarded'
    },
    {
        id:8,
        propertyName:'Experion The Westerlies',
        location:'St. 163, Sector-108 Gurgaon',
        feild1:'Developer Name',
        feild2:'Client Name',
        feild3:'Attendee Name',
        // feild4:'Unit Number',
        feild5:'Request Date',
        feild6:'Status',
        BrokerName:'Rajan Pathak',
        ClientName:'Abhinav',
        Attendee:'Umair',
        // UnitNumber:'12A',
        RequestDate:'12-04-2020',
        Status:'Pending'
    },
    {
        id:9,
        propertyName:'Experion The Westerlies',
        location:'St. 163, Sector-108 Gurgaon',
        feild1:'Developer Name',
        feild2:'Client Name',
        feild3:'Attendee Name',
        // feild4:'Unit Number',
        feild5:'Request Date',
        feild6:'Status',
        BrokerName:'Rajan Pathak',
        ClientName:'Abhinav',
        Attendee:'Umair',
        // UnitNumber:'12A',
        RequestDate:'12-04-2020',
        Status:'Pending'
    },
    {
        id:10,
        propertyName:'Experion The Westerlies',
        location:'St. 163, Sector-108 Gurgaon',
        feild1:'Developer Name',
        feild2:'Client Name',
        feild3:'Attendee Name',
        // feild4:'Unit Number',
        feild5:'Request Date',
        feild6:'Status',
        BrokerName:'Rajan Pathak',
        ClientName:'Abhinav',
        Attendee:'Umair',
        // UnitNumber:'12A',
        RequestDate:'12-04-2020',
        Status:'Pending'
    },
    {
        id:11,
        propertyName:'Experion The Westerlies',
        location:'St. 163, Sector-108 Gurgaon',
        feild1:'Developer Name',
        feild2:'Client Name',
        feild3:'Attendee Name',
        // feild4:'Unit Number',
        feild5:'Request Date',
        feild6:'Status',
        BrokerName:'Rajan Pathak',
        ClientName:'Abhinav',
        Attendee:'Umair',
        // UnitNumber:'12A',
        RequestDate:'12-04-2020',
        Status:'Pending'
    },
    {
        id:12,
        propertyName:'Experion The Westerlies',
        location:'St. 163, Sector-108 Gurgaon',
        feild1:'Developer Name',
        feild2:'Client Name',
        feild3:'Attendee Name',
        // feild4:'Unit Number',
        feild5:'Request Date',
        feild6:'Status',
        BrokerName:'Rajan Pathak',
        ClientName:'Abhinav',
        Attendee:'Umair',
        // UnitNumber:'12A',
        RequestDate:'12-04-2020',
        Status:'Pending'
    },
    {
        id:13,
        propertyName:'Experion The Westerlies',
        location:'St. 163, Sector-108 Gurgaon',
        feild1:'Developer Name',
        feild2:'Client Name',
        feild3:'Attendee Name',
        // feild4:'Unit Number',
        feild5:'Request Date',
        feild6:'Status',
        BrokerName:'Rajan Pathak',
        ClientName:'Abhinav',
        Attendee:'Umair',
        // UnitNumber:'12A',
        RequestDate:'12-04-2020',
        Status:'Approved'
    },
    {
        id:14,
        propertyName:'Experion The Westerlies',
        location:'St. 163, Sector-108 Gurgaon',
        feild1:'Developer Name',
        feild2:'Client Name',
        feild3:'Attendee Name',
        // feild4:'Unit Number',
        feild5:'Request Date',
        feild6:'Status',
        BrokerName:'Rajan Pathak',
        ClientName:'Abhinav',
        Attendee:'Umair',
        // UnitNumber:'12A',
        RequestDate:'11-04-2020',
        Status:'Approved'
    },
    {
        id:15,
        propertyName:'Experion The Westerlies',
        location:'St. 163, Sector-108 Gurgaon',
        feild1:'Developer Name',
        feild2:'Client Name',
        feild3:'Attendee Name',
        // feild4:'Unit Number',
        feild5:'Request Date',
        feild6:'Status',
        BrokerName:'Rajan Pathak',
        ClientName:'Abhinav',
        Attendee:'Umair',
        // UnitNumber:'12A',
        RequestDate:'12-04-2020',
        Status:'Approved'
    },
    {
        id:16,
        propertyName:'Experion The Westerlies',
        location:'St. 163, Sector-108 Gurgaon',
        feild1:'Developer Name',
        feild2:'Client Name',
        feild3:'Attendee Name',
        // feild4:'Unit Number',
        feild5:'Request Date',
        feild6:'Status',
        BrokerName:'Rajan Pathak',
        ClientName:'Abhinav',
        Attendee:'Umair',
        // UnitNumber:'12A',
        RequestDate:'12-04-2020',
        Status:'Approved'
    },
    {
        id:17,
        propertyName:'Experion The Westerlies',
        location:'St. 163, Sector-108 Gurgaon',
        feild1:'Developer Name',
        feild2:'Client Name',
        feild3:'Attendee Name',
        // feild4:'Unit Number',
        feild5:'Request Date',
        feild6:'Status',
        BrokerName:'Rajan Pathak',
        ClientName:'Abhinav',
        Attendee:'Umair',
        // UnitNumber:'12A',
        RequestDate:'11-04-2020',
        Status:'Approved'
    },
    {
        id:18,
        propertyName:'Experion The Westerlies',
        location:'St. 163, Sector-108 Gurgaon',
        feild1:'Developer Name',
        feild2:'Client Name',
        feild3:'Attendee Name',
        // feild4:'Unit Number',
        feild5:'Request Date',
        feild6:'Status',
        BrokerName:'Rajan Pathak',
        ClientName:'Abhinav',
        Attendee:'Umair',
        // UnitNumber:'12A',
        RequestDate:'11-04-2020',
        Status:'Declined'
    },
    {
        id:19,
        propertyName:'Experion The Westerlies',
        location:'St. 163, Sector-108 Gurgaon',
        feild1:'Developer Name',
        feild2:'Client Name',
        feild3:'Attendee Name',
        // feild4:'Unit Number',
        feild5:'Request Date',
        feild6:'Status',
        BrokerName:'Rajan Pathak',
        ClientName:'Abhinav',
        Attendee:'Umair',
        // UnitNumber:'12A',
        RequestDate:'11-04-2020',
        Status:'Rewarded'
    },
    
]